id: IE725F464
legacy_id: P009187
ocr_import_info:
  bdrc_scan_id: W3CN2914
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T19:58:43'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T13:13:33.038039+00:00'
last_modified: 2022-09-03 21:14:53.887441
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN2914
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW3CN2914
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། པདྨ་དཀར་པོ།
  author: འབྲུག་ཆེན ༠༤་པདྨ་དཀར་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.6638352309400387
  ocr_word_median_confidence_index: 0.7200000286102295
quality: null
bases:
  I3CN2918:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN2918
      total_pages: 435
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3CN2918.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6912635944984264
    legacy_id: v003
  I3CN2919:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN2919
      total_pages: 308
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3CN2919.txt
    statistics:
      ocr_word_median_confidence_index: 0.5799999833106995
      ocr_word_mean_confidence_index: 0.5780223842548114
    legacy_id: v004
  I3CN2923:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN2923
      total_pages: 282
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I3CN2923.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6414208669714526
    legacy_id: v008
  I3CN2920:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN2920
      total_pages: 220
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I3CN2920.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6833260345706417
    legacy_id: v005
  I3CN2924:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN2924
      total_pages: 338
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I3CN2924.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6263899714166714
    legacy_id: v009
  I3CN2922:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN2922
      total_pages: 448
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I3CN2922.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7330908588767384
    legacy_id: v007
  I3CN2921:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN2921
      total_pages: 306
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I3CN2921.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5650767140998394
    legacy_id: v006
  I3CN2917:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN2917
      total_pages: 304
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN2917.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.6797085489544251
    legacy_id: v002
  I3CN2916:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN2916
      total_pages: 456
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN2916.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7372629159425421
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
