id: IE725F464
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T20:01:21+00:00'
last_modified: '2022-06-08T09:14:20.792720+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN2914
  title: གསུང་འབུམ། པདྨ་དཀར་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E55C:
      image_group_id: I3CN2916
      title: ''
      total_pages: 456
      order: 1
      base_file: E55C.txt
    659E:
      image_group_id: I3CN2917
      title: ''
      total_pages: 304
      order: 2
      base_file: 659E.txt
    AA3D:
      image_group_id: I3CN2918
      title: ''
      total_pages: 435
      order: 3
      base_file: AA3D.txt
    FAF7:
      image_group_id: I3CN2919
      title: ''
      total_pages: 308
      order: 4
      base_file: FAF7.txt
    D542:
      image_group_id: I3CN2920
      title: ''
      total_pages: 220
      order: 5
      base_file: D542.txt
    '4955':
      image_group_id: I3CN2921
      title: ''
      total_pages: 306
      order: 6
      base_file: 4955.txt
    4D48:
      image_group_id: I3CN2922
      title: ''
      total_pages: 448
      order: 7
      base_file: 4D48.txt
    147D:
      image_group_id: I3CN2923
      title: ''
      total_pages: 282
      order: 8
      base_file: 147D.txt
    EF22:
      image_group_id: I3CN2924
      title: ''
      total_pages: 338
      order: 9
      base_file: EF22.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
